package org.iris.ia.tools;

import org.iris.ia.agent.AISummaryAgent;
import org.iris.ia.dto.AISummary;

import dev.langchain4j.agent.tool.Tool;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

@ApplicationScoped
public class AISummaryTool {
    @Inject
    AISummaryAgent aiSummaryAgent;

    @Tool("""
        USE this tool only if you have the question and the data to analyze.
        Generates a summary and recommendations based on the analysis of the question and the data provided.
        Use this tool when you have the question and the data to analyze, and you need to generate a concise and informative summary with actionable recommendations for the user.

        PARAMETERS:
        - question: The question to analyze.
        - data: The data to analyze, which can be the answer generated by the ClinicalFhirAgent
        or any other relevant data that can help in the analysis.
    """)
    public AISummary generateSummary(String question, String data) {
        return aiSummaryAgent.summary(question, data);
    }
}
